In [11]:
pip install prophet

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: prophet in c:\users\mine\appdata\roaming\python\python312\site-packages (1.3.0)
Requirement already satisfied: cmdstanpy>=1.0.4 in c:\users\mine\appdata\roaming\python\python312\site-packages (from prophet) (1.3.0)
Requirement already satisfied: numpy>=1.15.4 in c:\programdata\new\anaconda3\lib\site-packages (from prophet) (1.26.4)
Requirement already satisfied: matplotlib>=2.0.0 in c:\programdata\new\anaconda3\lib\site-packages (from prophet) (3.9.2)
Requirement already satisfied: pandas>=1.0.4 in c:\programdata\new\anaconda3\lib\site-packages (from prophet) (2.2.2)
Requirement already satisfied: holidays<1,>=0.25 in c:\users\mine\appdata\roaming\python\python312\site-packages (from prophet) (0.102)
Requirement already satisfied: tqdm>=4.36.1 in c:\programdata\new\anaconda3\lib\site-packages (from prophet) (4.66.5)
Requirement already satisfied: importlib_resources in c:\users\mine\appdata\roaming\python\python312\site-packages (from prophet) (7.1.0)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in c:\users\mine\appdata\roaming\python\python312\site-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in c:\programdata\new\anaconda3\lib\site-packages (from holidays<1,>=0.25->prophet) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\new\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\new\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\new\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\new\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\new\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (24.1)
Requirement already satisfied: pillow>=8 in c:\programdata\new\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\new\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (3.1.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\new\anaconda3\lib\site-packages (from pandas>=1.0.4->prophet) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\new\anaconda3\lib\site-packages (from pandas>=1.0.4->prophet) (2023.3)
Requirement already satisfied: colorama in c:\programdata\new\anaconda3\lib\site-packages (from tqdm>=4.36.1->prophet) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\programdata\new\anaconda3\lib\site-packages (from python-dateutil<3,>=2.9.0.post0->holidays<1,>=0.25->prophet) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import joblib
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error,root_mean_squared_error, r2_score
from prophet import Prophet

In [3]:
df= joblib.load(r"C:\Users\MINE\Desktop\Air passenger prediction\dataset\df.pkl")

if 'Month' not in df.columns and df.index.name == 'Month':
    df = df.reset_index()

In [4]:
df.head()

,Month,#Passengers,month,quater,lag1,lag2,lag3,rolling_mean3,rolling_std3,rolling_mean6,rolling_std6
0,1949-01-01,112,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1949-02-01,118,2,1,112.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1949-03-01,132,3,1,118.0,112.0,NaN,120.666667,10.263203,NaN,NaN
3,1949-04-01,129,4,2,132.0,118.0,112.0,126.333333,7.371115,NaN,NaN
4,1949-05-01,121,5,2,129.0,132.0,118.0,127.333333,5.686241,NaN,NaN

In [5]:

df = df.rename(columns={'Month': 'ds', '#Passengers': 'y'})

df['ds'] = pd.to_datetime(df['ds'], errors='coerce')
df['y'] = pd.to_numeric(df['y'], errors='coerce')


df= df.iloc[:, 0:2]

In [6]:
df.shape

(118, 2)

In [7]:
df.head()

          ds    y
0 1949-01-01  112
1 1949-02-01  118
2 1949-03-01  132
3 1949-04-01  129
4 1949-05-01  121

In [8]:
test = df.tail(12).copy()
train = df.iloc[:-12].copy()

In [9]:
train.head()

          ds    y
0 1949-01-01  112
1 1949-02-01  118
2 1949-03-01  132
3 1949-04-01  129
4 1949-05-01  121

In [10]:
train.isna().sum()

ds    0
y     0
dtype: int64

In [ ]:
model= Prophet(changepoint_prior_scale= 0.05,
                seasonality_mode='multiplicative',
                seasonality_prior_scale= 10,
                yearly_seasonality= True,
                weekly_seasonality= False,
                daily_seasonality= False
                )
model.fit(train)
model.stan_backend= None

08:54:35 - cmdstanpy - INFO - Chain [1] start processing
08:54:38 - cmdstanpy - INFO - Chain [1] done processing
08:54:38 - cmdstanpy - ERROR - Chain [1] error: code '3221225785'
Optimization terminated abnormally. Falling back to Newton.
08:54:38 - cmdstanpy - INFO - Chain [1] start processing
08:54:40 - cmdstanpy - INFO - Chain [1] done processing
08:54:40 - cmdstanpy - ERROR - Chain [1] error: code '3221225785'

RuntimeError: Error during optimization! Command 'C:\Users\MINE\AppData\Roaming\Python\Python312\site-packages\prophet\stan_model\prophet_model.bin random seed=98352 data file=C:\Users\MINE\AppData\Local\Temp\tmpcwk4w3gv\jzh3115p.json init=C:\Users\MINE\AppData\Local\Temp\tmpcwk4w3gv\3d2dyhc1.json output file=C:\Users\MINE\AppData\Local\Temp\tmpcwk4w3gv\prophet_modelrrbp6xio\prophet_model-20260817085438.csv method=optimize algorithm=newton iter=10000' failed:

In [ ]:
future= model.make_future_dataframe(periods=12,freq='MS')
forecast= model.predict(future)

KeyError: 'k'